// ============================================================
// COMPÊNDIO DE TALENTOS — DATA
// Arquivo: js/compendium/data-talents.js
// ============================================================

const TALENTOS_DATA = [

    // ─── COMBATE ───────────────────────────────────────────
    {
        id: 'adepto-marcial',
        nome: 'Adepto Marcial',
        categoria: 'combate',
        icone: '⚔️',
        prereq: '',
        descricao: 'Treinamento marcial avançado que permite realizar manobras de combate especiais do arquétipo Mestre de Batalha.',
        beneficios: [
            'Aprende duas manobras à sua escolha da lista do Mestre de Batalha.',
            'CD das manobras: 8 + bônus de proficiência + mod. de Força ou Destreza.',
            'Ganha 1 dado de superioridade d6 (ou mais 1 se já possuir); recuperado em descanso curto ou longo.',
        ],
    },
    {
        id: 'alerta',
        nome: 'Alerta',
        categoria: 'combate',
        icone: '👁️',
        prereq: '',
        descricao: 'Sempre atento ao perigo, você reage mais rápido e nunca é pego de surpresa.',
        beneficios: [
            '+5 de bônus em iniciativa.',
            'Não pode ser surpreendido enquanto estiver consciente.',
            'Outras criaturas não ganham vantagem em ataques por não serem visíveis para você.',
        ],
    },
    {
        id: 'ambidestro',
        nome: 'Ambidestro',
        categoria: 'combate',
        icone: '🗡️',
        prereq: '',
        descricao: 'Domínio do estilo com duas armas, oferecendo proteção e velocidade de ataque superiores.',
        beneficios: [
            '+1 de bônus na CA enquanto empunhar uma arma corpo a corpo em cada mão.',
            'Pode usar combater com duas armas mesmo que a arma não seja leve.',
            'Pode sacar ou guardar duas armas de uma mão de uma só vez.',
        ],
    },
    {
        id: 'atacante-bestial',
        nome: 'Atacante Bestial',
        categoria: 'combate',
        icone: '🐾',
        prereq: '',
        descricao: 'Seus golpes corpo a corpo são devastadores — você pode repetir o dado de dano e escolher o melhor resultado.',
        beneficios: [
            'Ao rolar dano em ataque corpo a corpo com arma, pode relançar o dado de dano da arma e usar qualquer dos valores.',
        ],
    },
    {
        id: 'atirador-aguçado',
        nome: 'Atirador Aguçado',
        categoria: 'combate',
        icone: '🏹',
        prereq: '',
        descricao: 'Domínio total de armas à distância: ignore alcance, cobertura e troque precisão por poder de fogo.',
        beneficios: [
            'Atacar além do alcance normal não impõe desvantagem.',
            'Ataques à distância ignoram meia-cobertura e três-quartos de cobertura.',
            'Pode sofrer –5 na jogada de ataque para ganhar +10 no dano.',
        ],
    },
    {
        id: 'combatente-montado',
        nome: 'Combatente Montado',
        categoria: 'combate',
        icone: '🐴',
        prereq: '',
        descricao: 'Oponente perigoso quando montado, com vantagem sobre alvos menores e proteção para a montaria.',
        beneficios: [
            'Vantagem em ataques corpo a corpo contra criaturas desmontadas menores que sua montaria.',
            'Pode forçar ataques direcionados à montaria para si mesmo.',
            'Sua montaria não sofre dano em testes de resistência de Destreza bem-sucedidos.',
        ],
    },
    {
        id: 'duelista-defensivo',
        nome: 'Duelista Defensivo',
        categoria: 'combate',
        icone: '🤺',
        prereq: 'Destreza 13 ou maior',
        descricao: 'Ao ser atingido por ataque corpo a corpo, usa sua reação para adicionar o bônus de proficiência à CA.',
        beneficios: [
            'Reação: adiciona o bônus de proficiência à CA quando atingido por ataque corpo a corpo.',
            'Requer empunhar uma arma de acuidade com proficiência.',
        ],
    },
    {
        id: 'envenenador',
        nome: 'Envenenador',
        categoria: 'combate',
        icone: '🧪',
        prereq: '',
        descricao: 'Mestre na criação e aplicação de venenos letais que ignoram resistências.',
        beneficios: [
            'Dano venenoso ignora resistências.',
            'Aplica veneno com ação bônus em vez de ação.',
            'Proficiência com kit de envenenador.',
            'Cria doses de veneno (CD 14, 2d8 venenoso + envenenado) com 1 hora de trabalho e 50 po.',
        ],
    },
    {
        id: 'esmagador',
        nome: 'Esmagador',
        categoria: 'combate',
        icone: '🔨',
        prereq: '',
        descricao: 'Especialista em dano contundente: empurra inimigos e explora críticos para dominar o campo de batalha.',
        beneficios: [
            '+1 em Força ou Constituição (máx. 20).',
            'Uma vez por turno, ao acertar dano contundente, pode mover o alvo até 1,5 m.',
            'Ao acertar um crítico com dano contundente, ataques subsequentes contra o alvo têm vantagem até seu próximo turno.',
        ],
    },
    {
        id: 'especialista-besta',
        nome: 'Especialista em Besta',
        categoria: 'combate',
        icone: '🔫',
        prereq: '',
        descricao: 'Domínio completo de bestas: ignore a recarga, atire próximo a inimigos e use ação bônus para atacar.',
        beneficios: [
            'Ignora a qualidade de recarga de bestas com proficiência.',
            'Estar a 1,5 m de inimigos não impõe desvantagem nos ataques.',
            'Ao usar ação de Ataque com arma de uma mão, pode usar ação bônus para atacar com besta de mão.',
        ],
    },
    {
        id: 'especialista-briga',
        nome: 'Especialista em Briga',
        categoria: 'combate',
        icone: '👊',
        prereq: '',
        descricao: 'Veterano de brigas usando qualquer coisa como arma. Seus golpes desarmados causam mais dano.',
        beneficios: [
            '+1 em Força ou Constituição (máx. 20).',
            'Ataques desarmados ou com armas improvisadas causam 1d4 de dano extra.',
            'Ao acertar ataque desarmado ou improvisado, ação bônus para tentar agarrar o alvo.',
        ],
    },
    {
        id: 'imobilizador',
        nome: 'Imobilizador',
        categoria: 'combate',
        icone: '🪢',
        prereq: 'Força 13 ou maior',
        descricao: 'Especialista em prender e imobilizar oponentes em combate engajado.',
        beneficios: [
            'Vantagem em jogadas de ataque contra criaturas agarradas.',
            'Ação: pode imobilizar criatura agarrada com outro teste de agarrar (ambos ficam impedidos).',
        ],
    },
    {
        id: 'iniciado-combate',
        nome: 'Iniciado em Combate',
        categoria: 'combate',
        icone: '🛡️',
        prereq: 'Proficiência com arma marcial',
        descricao: 'Treinamento marcial único que ensina um Estilo de Luta da lista do guerreiro.',
        beneficios: [
            '+1 em Força ou Destreza (máx. 20).',
            'Aprende um Estilo de Luta à escolha da lista do guerreiro.',
            'Pode trocar o estilo ao subir de nível.',
        ],
    },
    {
        id: 'investida-poderosa',
        nome: 'Investida Poderosa',
        categoria: 'combate',
        icone: '💨',
        prereq: '',
        descricao: 'Ao usar Disparada, pode atacar ou empurrar com ação bônus — e ganhar bônus ao se mover antes.',
        beneficios: [
            'Ao usar Disparada, ação bônus para atacar corpo a corpo ou empurrar.',
            'Se mover pelo menos 3 m antes do ataque: +5 no dano ou empurra até 3 m.',
        ],
    },
    {
        id: 'lacerador',
        nome: 'Lacerador',
        categoria: 'combate',
        icone: '🗡️',
        prereq: '',
        descricao: 'Cortes precisos reduzem o deslocamento do inimigo e impõem desvantagem em críticos.',
        beneficios: [
            '+1 em Força ou Destreza (máx. 20).',
            'Uma vez por turno, ao acertar dano cortante, reduz deslocamento do alvo em 3 m até seu próximo turno.',
            'Crítico com dano cortante: alvo sofre desvantagem em ataques até o próximo turno.',
        ],
    },
    {
        id: 'maestria-arma-haste',
        nome: 'Maestria em Arma de Haste',
        categoria: 'combate',
        icone: '🪄',
        prereq: '',
        descricao: 'Mantém inimigos afastados e ataca com a extremidade oposta como ação bônus.',
        beneficios: [
            'Ao atacar com glaive, alabarda ou bordão, ação bônus para atacar com a outra extremidade (1d4 contundente).',
            'Criaturas que entrarem no seu alcance enquanto empunha armas de haste provocam ataques de oportunidade.',
        ],
    },
    {
        id: 'matador-conjuradores',
        nome: 'Matador de Conjuradores',
        categoria: 'combate',
        icone: '🔮',
        prereq: '',
        descricao: 'Técnicas especializadas para combater conjuradores em distâncias curtas.',
        beneficios: [
            'Reação: ao ver criatura a até 1,5 m conjurar, pode realizar ataque corpo a corpo contra ela.',
            'Dano em criatura concentrada causa desvantagem no teste de concentração.',
            'Vantagem em testes de resistência contra magias de criaturas a até 1,5 m.',
        ],
    },
    {
        id: 'mestre-armas',
        nome: 'Mestre de Armas',
        categoria: 'combate',
        icone: '⚙️',
        prereq: '',
        descricao: 'Treinamento extensivo com uma variedade de armas simples e marciais.',
        beneficios: [
            '+1 em Força ou Destreza (máx. 20).',
            'Ganha proficiência com quatro armas simples ou marciais à escolha.',
        ],
    },
    {
        id: 'mestre-armas-grandes',
        nome: 'Mestre de Armas Grandes',
        categoria: 'combate',
        icone: '🪓',
        prereq: '',
        descricao: 'Usa o peso das armas pesadas a seu favor, com ataques bônus em críticos e dano devastador.',
        beneficios: [
            'Ao acertar crítico ou reduzir alvo a 0 PV, ação bônus para realizar outro ataque corpo a corpo.',
            'Pode sofrer –5 na jogada de ataque para ganhar +10 no dano com arma pesada.',
        ],
    },
    {
        id: 'mestre-escudo',
        nome: 'Mestre de Escudo',
        categoria: 'combate',
        icone: '🛡️',
        prereq: '',
        descricao: 'Usa o escudo como arma ofensiva e proteção extra contra magias e efeitos de área.',
        beneficios: [
            'Ação bônus para empurrar criaturas após usar a ação de Ataque.',
            'Adiciona o bônus de CA do escudo a testes de resistência de Destreza.',
            'Reação: ao passar no teste de resistência de Destreza, pode não sofrer nenhum dano.',
        ],
    },
    {
        id: 'mobilidade',
        nome: 'Mobilidade',
        categoria: 'combate',
        icone: '💨',
        prereq: '',
        descricao: 'Movimentação excepcional: mais velocidade, ignore terreno difícil ao disparar e evite contra-ataques.',
        beneficios: [
            'Deslocamento aumenta em 3 metros.',
            'Ao usar Disparada, terreno difícil não custa movimento adicional.',
            'Ao atacar uma criatura corpo a corpo, ela não provoca ataque de oportunidade de você pelo resto do turno.',
        ],
    },
    {
        id: 'perfurador',
        nome: 'Perfurador',
        categoria: 'combate',
        icone: '🗡️',
        prereq: '',
        descricao: 'Precisão cirúrgica com dano perfurante: relance dados e potencialize críticos.',
        beneficios: [
            '+1 em Força ou Destreza (máx. 20).',
            'Uma vez por turno, ao acertar dano perfurante, pode relançar um dado de dano e escolher o resultado.',
            'Crítico com dano perfurante: rola um dado de dano adicional.',
        ],
    },
    {
        id: 'pistoleiro',
        nome: 'Pistoleiro',
        categoria: 'combate',
        icone: '🔫',
        prereq: '',
        descricao: 'Mestre no uso de armas de fogo: ignora recarga e mira, e atira mesmo próximo a inimigos.',
        beneficios: [
            '+1 em Destreza (máx. 20).',
            'Proficiência com armas de fogo.',
            'Ignora as propriedades de recarga e mira.',
            'Não sofre desvantagem em ataques à distância a 1,5 m de criatura hostil.',
        ],
    },
    {
        id: 'sentinela',
        nome: 'Sentinela',
        categoria: 'combate',
        icone: '🗡️',
        prereq: '',
        descricao: 'Dominador do ataque de oportunidade: para inimigos na fuga, pune quem desengaja e protege aliados.',
        beneficios: [
            'Ao acertar ataque de oportunidade, o deslocamento da criatura se torna 0.',
            'Criaturas provocam ataque de oportunidade mesmo ao usar Desengajar.',
            'Reação: ao criatura atacar aliado a até 1,5 m, pode atacar o agressor.',
        ],
    },
    {
        id: 'tita-ataque',
        nome: 'Titã de Ataque',
        categoria: 'combate',
        icone: '💪',
        prereq: '',
        descricao: 'Força imparável no campo de batalha: ignore a propriedade de duas mãos e destrua em sequência.',
        beneficios: [
            'Pode ignorar a propriedade de duas mãos de armas pesadas.',
            'Ao se mover pelo menos 3 m antes de atacar, rola dano duas vezes e fica com o melhor.',
            'Ao acertar uma criatura, próximo ataque contra outra a até 3 m ganha bônus de dano igual ao nível.',
        ],
    },

    // ─── DEFESA ────────────────────────────────────────────
    {
        id: 'maestria-armadura-media',
        nome: 'Maestria em Armadura Média',
        categoria: 'defesa',
        icone: '🛡️',
        prereq: 'Proficiência em armadura média',
        descricao: 'Usa armadura média sem penalidade de furtividade e extrai o máximo de proteção com alta Destreza.',
        beneficios: [
            'Armadura média não impõe desvantagem em Furtividade.',
            'Com Destreza 16+, adiciona 3 à CA em vez de 2.',
        ],
    },
    {
        id: 'maestria-armadura-pesada',
        nome: 'Maestria em Armadura Pesada',
        categoria: 'defesa',
        icone: '⚔️',
        prereq: 'Proficiência em armadura pesada',
        descricao: 'Armadura pesada reduz dano físico não-mágico recebido em 3.',
        beneficios: [
            '+1 em Força (máx. 20).',
            'Dano de concussão, cortante e perfurante não-mágico recebido é reduzido em 3.',
        ],
    },
    {
        id: 'protecao-leve',
        nome: 'Proteção Leve',
        categoria: 'defesa',
        icone: '🧥',
        prereq: '',
        descricao: 'Treinamento com armaduras leves para os que ainda não possuem essa proficiência.',
        beneficios: [
            '+1 em Força ou Destreza (máx. 20).',
            'Ganha proficiência com armaduras leves.',
        ],
    },
    {
        id: 'protecao-moderada',
        nome: 'Proteção Moderada',
        categoria: 'defesa',
        icone: '🥋',
        prereq: 'Proficiência em armadura leve',
        descricao: 'Expande a proteção para armaduras médias e escudos.',
        beneficios: [
            '+1 em Força ou Destreza (máx. 20).',
            'Ganha proficiência com armaduras médias e escudos.',
        ],
    },
    {
        id: 'protecao-pesada',
        nome: 'Proteção Pesada',
        categoria: 'defesa',
        icone: '🏰',
        prereq: 'Proficiência em armadura média',
        descricao: 'Culminação do treinamento com armaduras — proficiência com as mais pesadas.',
        beneficios: [
            '+1 em Força (máx. 20).',
            'Ganha proficiência com armaduras pesadas.',
        ],
    },
    {
        id: 'protetor',
        nome: 'Protetor',
        categoria: 'defesa',
        icone: '🤝',
        prereq: 'Constituição 13 ou maior, Proficiência com escudos',
        descricao: 'Interpõe-se entre aliados e ataques, absorvendo o golpe no lugar deles.',
        beneficios: [
            '+1 em Constituição (máx. 20).',
            'Reação: interpõe-se em ataques contra aliados dentro do seu deslocamento, sofrendo o dano no lugar.',
            'Pode usar essa habilidade um número de vezes igual ao modificador de Destreza (recuperado em descanso).',
        ],
    },
    {
        id: 'resiliente',
        nome: 'Resiliente',
        categoria: 'defesa',
        icone: '💠',
        prereq: '',
        descricao: 'Fortalece um atributo e concede proficiência no teste de resistência correspondente.',
        beneficios: [
            '+1 no valor de habilidade escolhido (máx. 20).',
            'Ganha proficiência em testes de resistência com a habilidade escolhida.',
        ],
    },
    {
        id: 'resistente',
        nome: 'Resistente',
        categoria: 'defesa',
        icone: '🪨',
        prereq: '',
        descricao: 'Corpo endurecido que recupera mais PV ao gastar Dados de Vida.',
        beneficios: [
            '+1 em Constituição (máx. 20).',
            'Ao rolar Dado de Vida para recuperar PV, o mínimo é duas vezes o modificador de Constituição.',
        ],
    },
    {
        id: 'robusto',
        nome: 'Robusto',
        categoria: 'defesa',
        icone: '❤️',
        prereq: '',
        descricao: 'Reserva de PV muito maior — cresce a cada nível ganho.',
        beneficios: [
            '+1 em Constituição (máx. 20).',
            'Máximo de PV aumenta em 3 × nível atual ao adquirir o talento.',
            'Cada nível subsequente concede +3 PV adicionais.',
        ],
    },

    // ─── MAGIA ─────────────────────────────────────────────
    {
        id: 'adepto-elemental',
        nome: 'Adepto Elemental',
        categoria: 'magia',
        icone: '🔥',
        prereq: 'Capacidade de conjurar pelo menos uma magia',
        descricao: 'Domina um tipo de dano elemental, ignorando resistências e relançando dados com resultado 1.',
        beneficios: [
            'Escolha um tipo: ácido, elétrico, fogo, frio ou trovão.',
            'Suas magias ignoram resistência ao tipo escolhido.',
            'Ao rolar dano com esse tipo, pode relançar qualquer dado com resultado 1.',
            'Pode escolher esse talento múltiplas vezes para tipos diferentes.',
        ],
    },
    {
        id: 'adepto-metamagico',
        nome: 'Adepto Metamágico',
        categoria: 'magia',
        icone: '✨',
        prereq: 'Habilidade de Conjuração ou Magia de Pacto',
        descricao: 'Aprende duas opções de Metamagia da lista do feiticeiro e ganha pontos de feitiçaria.',
        beneficios: [
            'Aprende duas opções de Metamagia da lista do feiticeiro.',
            'Ganha 2 pontos de feitiçaria para usar com Metamagia.',
            'Pode substituir uma opção de Metamagia ao subir de nível.',
            'Recupera todos os pontos em descanso longo.',
        ],
    },
    {
        id: 'adepto-mistico',
        nome: 'Adepto Místico',
        categoria: 'magia',
        icone: '🌙',
        prereq: 'Habilidade de Conjuração ou Magia de Pacto',
        descricao: 'Desbloqueia uma Invocação Mística da classe do bruxo.',
        beneficios: [
            'Aprende uma Invocação Mística da lista do bruxo.',
            'Se a invocação tiver requisito, só pode escolhê-la se for bruxo e cumpri-lo.',
            'Pode trocar a invocação por outra ao subir de nível.',
        ],
    },
    {
        id: 'atirador-magia',
        nome: 'Atirador de Magia',
        categoria: 'magia',
        icone: '⚡',
        prereq: 'Capacidade de conjurar pelo menos uma magia',
        descricao: 'Magias de ataque com o dobro do alcance, ignorando coberturas.',
        beneficios: [
            'Magias que exigem jogada de ataque têm o alcance dobrado.',
            'Ataques à distância com magia ignoram meia-cobertura e três-quartos de cobertura.',
            'Aprende um truque de ataque de uma lista à escolha.',
        ],
    },
    {
        id: 'conjurador-guerra',
        nome: 'Conjurador de Guerra',
        categoria: 'magia',
        icone: '⚔️',
        prereq: 'Capacidade de conjurar pelo menos uma magia',
        descricao: 'Conjura magias no meio do combate com maestria, mantendo concentração e usando ataques de oportunidade mágicos.',
        beneficios: [
            'Vantagem em testes de Constituição para manter concentração após sofrer dano.',
            'Pode realizar componentes somáticos mesmo com armas ou escudo nas mãos.',
            'Reação: ao criatura provocar ataque de oportunidade, pode conjurar magia de 1 ação com um alvo no lugar.',
        ],
    },
    {
        id: 'conjurador-ritual',
        nome: 'Conjurador de Ritual',
        categoria: 'magia',
        icone: '📜',
        prereq: 'Inteligência ou Sabedoria 13 ou maior',
        descricao: 'Aprende e conjura magias como rituais a partir de um livro especial.',
        beneficios: [
            'Recebe um livro de rituais com duas magias de 1º nível com o descritor ritual.',
            'Escolha bardo, bruxo, clérigo, druida, feiticeiro ou mago para definir o atributo de conjuração.',
            'Pode adicionar magias rituais encontradas ao livro (2h + 50 po por nível).',
        ],
    },
    {
        id: 'iniciado-artifice',
        nome: 'Iniciado Artífice',
        categoria: 'magia',
        icone: '⚙️',
        prereq: '',
        descricao: 'Aprende habilidades dos artífices: um truque, uma magia de 1º nível e proficiência com ferramenta.',
        beneficios: [
            'Aprende um truque e uma magia de 1º círculo do artífice (Inteligência).',
            'Pode conjurar a magia de 1º círculo gratuitamente uma vez por descanso longo.',
            'Proficiência com um tipo de ferramenta de artesão (pode ser foco de conjuração).',
        ],
    },
    {
        id: 'iniciado-magia',
        nome: 'Iniciado em Magia',
        categoria: 'magia',
        icone: '📖',
        prereq: '',
        descricao: 'Aprende dois truques e uma magia de 1º nível de outra classe conjuradora.',
        beneficios: [
            'Escolha uma classe: bardo, bruxo, clérigo, druida, feiticeiro ou mago.',
            'Aprende dois truques da lista da classe escolhida.',
            'Aprende uma magia de 1º nível da mesma classe; pode conjurá-la uma vez por descanso longo.',
        ],
    },
    {
        id: 'telepático',
        nome: 'Telepático',
        categoria: 'magia',
        icone: '🧠',
        prereq: '',
        descricao: 'Comunica-se telepaticamente e lê pensamentos sem usar espaços de magia.',
        beneficios: [
            '+1 em Inteligência, Sabedoria ou Carisma (máx. 20).',
            'Fala telepaticamente com criaturas à vista até 18 m (deve conhecer o idioma).',
            'Pode conjurar Detectar Pensamentos sem espaço de magia ou componentes.',
        ],
    },
    {
        id: 'tocado-sombras',
        nome: 'Tocado pelas Sombras',
        categoria: 'magia',
        icone: '🌑',
        prereq: '',
        descricao: 'Magia sombria modificou você: aprende Invisibilidade e uma magia de ilusão ou necromancia.',
        beneficios: [
            '+1 em Inteligência, Sabedoria ou Carisma (máx. 20).',
            'Aprende Invisibilidade e uma magia de 1º círculo (Ilusão ou Necromancia).',
            'Pode conjurar ambas sem espaço de magia; recupera após descanso longo.',
        ],
    },

    // ─── HABILIDADE ────────────────────────────────────────
    {
        id: 'atleta',
        nome: 'Atleta',
        categoria: 'habilidade',
        icone: '🏃',
        prereq: '',
        descricao: 'Treinamento físico intenso melhora movimentação, escalada e saltos.',
        beneficios: [
            '+1 em Força ou Destreza (máx. 20).',
            'Se levantar do chão custa apenas 1,5 m de deslocamento.',
            'Escalar não custa deslocamento adicional.',
            'Salto em distância/altura com apenas 1,5 m de corrida.',
        ],
    },
    {
        id: 'explorador-cavernas',
        nome: 'Explorador de Cavernas',
        categoria: 'habilidade',
        icone: '🗺️',
        prereq: '',
        descricao: 'Detecta armadilhas e portas secretas com facilidade, e resiste melhor aos seus efeitos.',
        beneficios: [
            'Vantagem em Percepção e Investigação para detectar portas secretas.',
            'Vantagem em testes de resistência contra armadilhas.',
            'Resistência a dano causado por armadilhas.',
            'Pode procurar armadilhas em ritmo normal de viagem.',
        ],
    },
    {
        id: 'especializado-pericia',
        nome: 'Especializado em Perícia',
        categoria: 'habilidade',
        icone: '🎯',
        prereq: '',
        descricao: 'Aprimora uma perícia à escolha, concedendo especialidade e aumentando um atributo.',
        beneficios: [
            '+1 em um atributo à escolha (máx. 20).',
            'Proficiência em uma perícia à escolha.',
            'Especialidade em uma perícia com proficiência (dobra o bônus de proficiência).',
        ],
    },
    {
        id: 'mente-afiada',
        nome: 'Mente Afiada',
        categoria: 'habilidade',
        icone: '🧭',
        prereq: '',
        descricao: 'Memória perfeita e senso de orientação infalível — nunca se perde nem esquece nada.',
        beneficios: [
            '+1 em Inteligência (máx. 20).',
            'Sempre sabe a direção do norte.',
            'Sempre sabe o tempo restante para o próximo nascer ou pôr do sol.',
            'Recorda com precisão qualquer coisa vista ou ouvida no último mês.',
        ],
    },
    {
        id: 'observador',
        nome: 'Observador',
        categoria: 'habilidade',
        icone: '🔍',
        prereq: '',
        descricao: 'Percepção aguçada: lê lábios e possui altíssimos valores passivos de Percepção e Investigação.',
        beneficios: [
            '+1 em Inteligência ou Sabedoria (máx. 20).',
            'Pode ler lábios de criatura que fale idioma que compreenda.',
            '+5 nos valores passivos de Percepção e Investigação.',
        ],
    },
    {
        id: 'perito',
        nome: 'Perito',
        categoria: 'habilidade',
        icone: '📚',
        prereq: '',
        descricao: 'Proficiência em três perícias ou ferramentas à escolha.',
        beneficios: [
            'Ganha proficiência em qualquer combinação de três perícias ou ferramentas.',
        ],
    },
    {
        id: 'poliglota',
        nome: 'Poliglota',
        categoria: 'habilidade',
        icone: '🗣️',
        prereq: '',
        descricao: 'Domínio de idiomas e criptografia: aprende três línguas e cria códigos indecifráveis.',
        beneficios: [
            '+1 em Inteligência (máx. 20).',
            'Aprende três idiomas à escolha.',
            'Pode criar criptogramas: outros só decifram com sucesso em Inteligência (CD = Int + prof.) ou magia.',
        ],
    },
    {
        id: 'sorrateiro',
        nome: 'Sorrateiro',
        categoria: 'habilidade',
        icone: '🌑',
        prereq: 'Destreza 13 ou maior',
        descricao: 'Especialista em furtividade: se esconde na penumbra e mantém posição após errar ataques.',
        beneficios: [
            'Pode tentar se esconder quando estiver levemente obscurecido.',
            'Errar um ataque à distância estando escondido não revela sua posição.',
            'Penumbra não impõe desvantagem em testes de Percepção visual.',
        ],
    },

    // ─── GERAL ─────────────────────────────────────────────
    {
        id: 'ator',
        nome: 'Ator',
        categoria: 'geral',
        icone: '🎭',
        prereq: '',
        descricao: 'Mestre da mímica e do disfarce: vantagem em Atuação e Enganação ao se passar por outra pessoa.',
        beneficios: [
            '+1 em Carisma (máx. 20).',
            'Vantagem em Atuação e Enganação ao se disfarçar.',
            'Pode imitar a voz ou sons de qualquer criatura ouvida por ao menos 1 minuto.',
        ],
    },
    {
        id: 'chef',
        nome: 'Chef',
        categoria: 'geral',
        icone: '🍖',
        prereq: '',
        descricao: 'Cozinheiro habilidoso que prepara alimentos que curam e concedem PV temporários.',
        beneficios: [
            '+1 em Constituição ou Sabedoria (máx. 20).',
            'Proficiência com Utensílios de Cozinheiro.',
            'Descanso curto: prepara refeição para prof.+4 criaturas que recuperam 1d8 PV extras ao gastar Dados de Vida.',
            'Descanso longo: cria aperitivos (= bônus de prof.) que concedem PV temporários iguais ao bônus de proficiência.',
        ],
    },
    {
        id: 'curandeiro',
        nome: 'Curandeiro',
        categoria: 'geral',
        icone: '⚕️',
        prereq: '',
        descricao: 'Cirurgião capacitado que estabiliza aliados com PV e cura de forma eficiente.',
        beneficios: [
            'Ao estabilizar criatura morrendo com kit de primeiros-socorros, ela recupera 1 PV.',
            'Ação: gasta kit para restaurar 1d6+4 + Dados de Vida totais da criatura em PV (uma vez por descanso).',
        ],
    },
    {
        id: 'lider-inspirador',
        nome: 'Líder Inspirador',
        categoria: 'geral',
        icone: '👑',
        prereq: 'Carisma 13 ou maior',
        descricao: 'Inspira aliados com um discurso de 10 minutos, concedendo PV temporários.',
        beneficios: [
            '10 minutos: até 6 criaturas amigáveis recebem PV temporários = nível + mod. de Carisma.',
            'Criaturas só podem se beneficiar novamente após descanso curto ou longo.',
        ],
    },
    {
        id: 'sortudo',
        nome: 'Sortudo',
        categoria: 'geral',
        icone: '🍀',
        prereq: '',
        descricao: 'Sorte inexplicável: rerrole dados em momentos críticos usando pontos de sorte.',
        beneficios: [
            '3 pontos de sorte recuperados em descanso longo.',
            'Gasta 1 ponto para rolar d20 adicional em qualquer ataque, teste ou resistência — escolhendo qual usar.',
            'Também pode influenciar ataques de inimigos contra você.',
            'Pontos se cancelam se múltiplas criaturas os usam na mesma jogada.',
        ],
    },
];